version: '3'

services:
  linebot:
    build: .
    container_name: linebot
    expose:
      - "80"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - PORT=80
      - VIRTUAL_HOST=your.domain.com
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=your.domain.com
    volumes:
      - .:/app:delegated
      - /app/node_modules
      - /app/admin/logs
    restart: unless-stopped
    networks:
      - proxy-network

networks:
  proxy-network:
    external: true
